[BUGFIX] Migrate to Neos 3.0
neos/form-yamlbuilder pull request #4
Opened 2017-03-31 09:59 UTC by simonschaufi

Releases: master
Relates: https://github.com/SimplyAdmire/SimplyAdmire.Neos.FormBuilderBundle/pull/10

2017-03-31 13:37 UTC, kdambekalns approved these changes
Looks good. What about making the package use PSR-4 while it is being updated anyway?

2017-03-31 16:44 UTC, simonschaufi commented
Sure, I can do that. Could you make me a short checklist what needs to be done please?

2017-04-02 13:29 UTC, radmiraal commented
@simonschaufi change the autoload config in composer.json from:

```
		"psr-0": {
			"TYPO3\\FormBuilder": "Classes"
		}
```
to (mind the trailing slashes)
```
		"psr-4": {
			"Neos\\FormBuilder\\": "Classes"
		}
```

and then move all files from Classes/Neos/FormBuilder/ directly into the Classes folder

2017-04-02 23:39 UTC, simonschaufi commented
I changed super much and had to force push (don't know why). Can you review please?

2017-04-02 23:44 UTC, simonschaufi commented
Can somebody also take care about the new composer name? I don't know if anything needs to be done on packagist

2017-04-27 16:42 UTC, htuscher requested changes
Please remove all traces of typo3

2017-04-27 16:42 UTC, hhoechtl commented on Classes/Controller/EditorController.php
> + * This script belongs to the TYPO3 Flow package "Neos.FormBuilder".      *
Please use new header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Classes/Controller/FormManagerController.php
> + * This script belongs to the TYPO3 Flow package "Neos.FormBuilder".      *
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Classes/Controller/StandardController.php
> + * This script belongs to the TYPO3 Flow package "Neos.FormBuilder".      *
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Classes/ViewHelpers/JsonConfigurationViewHelper.php
> + * This script belongs to the TYPO3 Flow package "Neos.FormBuilder".      *
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on README.md
>  	TYPO3:
Please Change Namespace to Neos

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/app.coffee
>  TYPO3 = window.TYPO3 || {}
Please change to Neos

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/utility.coffee
> +# This script belongs to the TYPO3 Flow package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view.coffee
> +# This script belongs to the TYPO3 Flow package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/application.coffee
> +# This script belongs to the FLOW3 package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/elementOptionsPanel.coffee
> +# This script belongs to the FLOW3 package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/elementOptionsPanelEditors/basic.coffee
> +# This script belongs to the FLOW3 package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/elementOptionsPanelEditors/collectionEditor.coffee
> +# This script belongs to the FLOW3 package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/elementOptionsPanelEditors/finisher.coffee
> +# This script belongs to the FLOW3 package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/elementOptionsPanelEditors/grid.coffee
> +# This script belongs to the FLOW3 package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/elementOptionsPanelEditors/validator.coffee
> +# This script belongs to the FLOW3 package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/elementOptionsPanelEditors/validator.coffee
>  	classNames: ['typo3-formbuilder-validator-editor']
Please rename class without typo3

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/header.coffee
> +# This script belongs to the FLOW3 package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/insertElementsPanel.coffee
> +# This script belongs to the FLOW3 package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/stage.coffee
> +# This script belongs to the FLOW3 package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/CoffeeScript/view/structurePanel.coffee
> +# This script belongs to the FLOW3 package "Neos.FormBuilder".
Please use new file header (no TYPO3)

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/FormBuilderTemplates/Application.html
>  <section id="typo3-formbuilder-elementSidebar">
please remove typo3 from ids

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/FormBuilderTemplates/ElementOptionsPanel/FinisherEditor.html
>  <div class="typo3-formbuilder-addFinisher">
please remove typo3 from classname

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/FormBuilderTemplates/ElementOptionsPanel/IdentifierEditor.html
>  	<div class="typo3-formbuilder-controls">
please remove typo3 from classname

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/FormBuilderTemplates/ElementOptionsPanel/TextEditor.html
>  <div class="typo3-formbuilder-controlGroup">
please remove typo3 from classname

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/FormBuilderTemplates/ElementOptionsPanel/TextEditor.html
>  	<div class="typo3-formbuilder-controls">
please remove typo3 from classname

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/FormBuilderTemplates/ElementOptionsPanel/ValidatorEditor.html
>  <div class="typo3-formbuilder-addValidator">
please remove typo3 from classname

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/FormBuilderTemplates/Header.html
>  <ul id="typo3-formbuilder-toolbar">
please remove typo3 from classname

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/FormBuilderTemplates/InsertElementsPanel.html
>  	<h3 class="typo3-formbuilder-group-{{unbound content.key}}"><span>{{content.label}}</span></h3>
please remove typo3 from classname

2017-04-27 16:42 UTC, hhoechtl commented on Resources/Private/FormBuilderTemplates/Validator/MinimumMaximumEditor.html
>  	<div class="typo3-formbuilder-controls">
please remove typo3 from classname

2017-04-27 16:54 UTC, simonschaufi commented
If you want to, you can actually make changes in my code. Otherwise you need to wait some more time until i have done every change you requested.

2017-05-01 15:48 UTC, hhoechtl commented
I created a PR based on your changes to remove all traces of typo3 https://github.com/simonschaufi/form-builder/pull/1

2017-05-01 16:27 UTC, simonschaufi commented
thank you very much!

2017-05-01 16:31 UTC, htuscher approved these changes

2017-05-15 19:39 UTC, simonschaufi commented
can this be merged?

2017-05-24 23:03 UTC, albe commented
Let's do this :)

2017-05-24 23:03 UTC, merged

2017-05-25 07:50 UTC, simonschaufi commented
on packagist the composer name is still typo3/formbuilder but it should be neos/formbuilder. what needs to be done?

2017-05-25 20:35 UTC, albe commented
I guess someone with access on packagist needs to rename/move the package. @kdambekalns maybe?

2017-05-26 13:39 UTC, kdambekalns commented
Done.